// Provisions an ephemeral Neon database via neon-new and writes
// ATOMIK_DATABASE_URL to ../.env.local so subsequent runs can reuse it
// without reprovisioning. Run via `make db-provision`.

import { createDatabase } from './create-database';

console.log('Provisioning database...');

const { databaseUrl, claimUrl } = await createDatabase();

const lines = [
  '# Generated by `make db-provision` — do not commit.',
  `# Claim this instance to make it persistent: ${claimUrl}`,
  `ATOMIK_DATABASE_URL=${databaseUrl}`,
  '',
].join('\n');

const envPath = new URL('../.env.local', import.meta.url).pathname;
await Bun.write(envPath, lines);

console.log('Wrote .env.local');
console.log(`Claim URL: ${claimUrl}`);
console.log('');
console.log("Run 'make test-integration-local' to run tests against this database.");
